<h1 align="center">title: Md Akib Zabed Khan</h1>
<h3 align="center">description: Assistant Professor, Christopher Newport University</h3>
<h3 align="center">description: [Google Scholar profile of Dr. Khan](https://scholar.google.com/citations?user=wCqMfLEAAAAJ&hl=en)</h3>
theme: jekyll-theme-minimal
